# Import all models here so that Alembic can detect them when importing Base from models
from app.core.database import Base as Base
from app.models.user import User as User
from app.models.template import Template as Template
from app.models.project import Project as Project
from app.models.job import Job as Job
from app.models.design_history import DesignHistory as DesignHistory
from app.models.brand_kit import BrandKit as BrandKit
from app.models.credit_transaction import CreditTransaction as CreditTransaction
from app.models.ai_tool_result import AiToolResult as AiToolResult
from app.models.ai_tool_job import AiToolJob as AiToolJob
from app.models.ai_usage_event import AiUsageEvent as AiUsageEvent
from app.models.template_submission import TemplateSubmission as TemplateSubmission
from app.models.template_review import TemplateReview as TemplateReview
from app.models.template_version import TemplateVersion as TemplateVersion
from app.models.template_favorite import TemplateFavorite as TemplateFavorite
from app.models.template_usage_stat import TemplateUsageStat as TemplateUsageStat
from app.models.folder import Folder as Folder
from app.models.project_version import ProjectVersion as ProjectVersion
from app.models.brand_memory import BrandMemory as BrandMemory
from app.models.storage_purchase import StoragePurchase as StoragePurchase
from app.models.storage_quota_ledger import StorageQuotaLedger as StorageQuotaLedger
from app.models.waitlist_entry import WaitlistEntry as WaitlistEntry
from app.models.testimonial import Testimonial as Testimonial
from app.models.comparison_session import ComparisonSession as ComparisonSession
from app.models.referral import Referral as Referral
