[pytest]
asyncio_mode = strict
filterwarnings =
    ignore::FutureWarning
    ignore::RuntimeWarning:sklearn.*
    ignore::RuntimeWarning:numpy.*
    ignore::pydantic.PydanticDeprecatedSince212
    ignore:The "middleware" file convention is deprecated:UserWarning

