[pytest]
asyncio_mode = strict
filterwarnings =
    ignore::FutureWarning
    ignore::RuntimeWarning:sklearn.*
    ignore::RuntimeWarning:numpy.*
    ignore:Boto3 will no longer support Python 3.9.*:Warning
    ignore:.*PydanticDeprecatedSince212.*:Warning
    ignore:.*model_validator.*deprecated.*:Warning
    ignore:The "middleware" file convention is deprecated:UserWarning

