"""Seed 10 design templates for UMKM use cases."""

import asyncio
import uuid
from app.core.database import AsyncSessionLocal
from app.models.template import Template
from sqlalchemy.future import select

TEMPLATES = [
    # 🍔 Food & Beverage
    {
        "name": "Promo Spesial Makanan",
        "category": "food",
        "aspect_ratio": "1:1",
        "style": "bold",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.15,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 52,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.30,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 24,
                "color": "#FFD700",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 20,
                "color": "#FFFFFF",
                "bg_box": "rgba(220,38,38,0.9)",
            },
        ],
        "prompt_suffix": "appetizing food photography, vibrant colors, dark moody background, Rembrandt rim lighting, shot on 100mm macro f/2.8, PBR food textures, 8k photorealistic",
        "thumbnail_url": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=600&fit=crop",
    },
    {
        "name": "Menu Restoran Malam",
        "category": "food",
        "aspect_ratio": "9:16",
        "style": "elegant",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.10,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 44,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.22,
                "font_family": "Inter",
                "font_weight": 300,
                "font_size": 20,
                "color": "#E5E7EB",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.90,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FCD34D",
            },
        ],
        "prompt_suffix": "restaurant ambiance, warm ambient tungsten lighting, elegant table setting, shallow depth of field, 85mm f/1.4, cinematic bokeh glow",
        "thumbnail_url": "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=450&h=800&fit=crop",
    },
    {
        "name": "Diskon Minuman Dingin",
        "category": "food",
        "aspect_ratio": "1:1",
        "style": "playful",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.2,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 48,
                "color": "#1E3A8A",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.35,
                "font_family": "Inter",
                "font_weight": 500,
                "font_size": 24,
                "color": "#2563EB",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.8,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 20,
                "color": "#FFFFFF",
                "bg_box": "rgba(59,130,246,0.9)",
            },
        ],
        "prompt_suffix": "refreshing cold drink, high-speed splashing water photography, bright summer sunlight, hyper-realistic condensation drops, studio product lighting, 100mm macro f/2.8",
        "thumbnail_url": "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&h=600&fit=crop",
    },
    {
        "name": "Kopi Pagi - Lanskap",
        "category": "food",
        "aspect_ratio": "16:9",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.3,
                "y": 0.3,
                "font_family": "Inter",
                "font_weight": 700,
                "font_size": 52,
                "color": "#451A03",
            },
            {
                "role": "sub_headline",
                "x": 0.3,
                "y": 0.5,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 24,
                "color": "#78350F",
            },
            {
                "role": "cta",
                "x": 0.3,
                "y": 0.7,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FFFFFF",
                "bg_box": "rgba(146,64,14,0.9)",
            },
        ],
        "prompt_suffix": "coffee cup, perfect latte art, warm golden hour morning light, rustic wooden table texture, subsurface scattering on foam, 50mm f/1.8, cozy cafe aesthetic",
        "thumbnail_url": "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&h=450&fit=crop",
    },
    # 🛍️ Flash Sale / Discount
    {
        "name": "Mega Sale - Square",
        "category": "sale",
        "aspect_ratio": "1:1",
        "style": "bold",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.20,
                "font_family": "Poppins",
                "font_weight": 900,
                "font_size": 60,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.40,
                "font_family": "Inter",
                "font_weight": 500,
                "font_size": 28,
                "color": "#FEF08A",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.80,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 22,
                "color": "#FFFFFF",
                "bg_box": "rgba(239,68,68,0.95)",
            },
        ],
        "prompt_suffix": "sale event, vibrant red and yellow tones, explosive dynamic energy, floating shopping bags, 3D abstract geometry, high contrast studio lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=600&fit=crop",
    },
    {
        "name": "Flash Sale Weekend",
        "category": "sale",
        "aspect_ratio": "9:16",
        "style": "playful",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.12,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 48,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.25,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 22,
                "color": "#FDE68A",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.88,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 20,
                "color": "#1E293B",
                "bg_box": "rgba(250,204,21,0.95)",
            },
        ],
        "prompt_suffix": "flash sale, floating confetti dynamics, bright saturated colors, fun playful energy, glowing neon discount tags, softbox diffused lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1620241608701-94efd3cb8534?w=450&h=800&fit=crop",
    },
    {
        "name": "Cuci Gudang Akhir Tahun",
        "category": "sale",
        "aspect_ratio": "16:9",
        "style": "bold",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.3,
                "font_family": "Poppins",
                "font_weight": 900,
                "font_size": 56,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.5,
                "font_family": "Inter",
                "font_weight": 500,
                "font_size": 24,
                "color": "#D1D5DB",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.8,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 22,
                "color": "#000000",
                "bg_box": "rgba(255,255,255,0.9)",
            },
        ],
        "prompt_suffix": "clearance sale, warehouse background, 3D abstract geometric shapes, yellow and black color grading, high contrast harsh directional lighting, dramatic shadows",
        "thumbnail_url": "https://images.unsplash.com/photo-1555529771-835f59bfc50c?w=800&h=450&fit=crop",
    },
    # 📱 Product / E-commerce
    {
        "name": "Koleksi Fashion Baru",
        "category": "product",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.15,
                "font_family": "Playfair Display",
                "font_weight": 700,
                "font_size": 42,
                "color": "#FFFFFF",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.25,
                "font_family": "Inter",
                "font_weight": 300,
                "font_size": 18,
                "color": "#E5E7EB",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Inter",
                "font_weight": 500,
                "font_size": 16,
                "color": "#000000",
                "bg_box": "rgba(255,255,255,0.9)",
            },
        ],
        "prompt_suffix": "editorial fashion photography, large softbox diffused lighting, minimal cyclorama background, high end fashion, realistic fabric textures, 85mm f/1.8 lens, Vogue magazine style, 8k photorealistic",
        "thumbnail_url": "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&h=600&fit=crop",
    },
    {
        "name": "Gadget & Tech Banner",
        "category": "product",
        "aspect_ratio": "16:9",
        "style": "bold",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.3,
                "y": 0.35,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 48,
                "color": "#FFFFFF",
            },
            {
                "role": "sub_headline",
                "x": 0.3,
                "y": 0.55,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 20,
                "color": "#94A3B8",
            },
            {
                "role": "cta",
                "x": 0.3,
                "y": 0.75,
                "font_family": "Poppins",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FFFFFF",
                "bg_box": "rgba(59,130,246,0.9)",
            },
        ],
        "prompt_suffix": "modern gadgets, cyberpunk neon lighting, volumetric blue and purple fog, sleek dark technology, hovering devices, Octane render, glossy metallic materials",
        "thumbnail_url": "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&h=450&fit=crop",
    },
    {
        "name": "Kosmetik - Instagram Story",
        "category": "product",
        "aspect_ratio": "9:16",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.12,
                "font_family": "Poppins",
                "font_weight": 600,
                "font_size": 40,
                "color": "#475569",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.22,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 20,
                "color": "#94A3B8",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.88,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 16,
                "color": "#FFFFFF",
                "bg_box": "rgba(244,114,182,0.9)",
            },
        ],
        "prompt_suffix": "cosmetics skin care product mockup, pastel pink background, soft reflections, caustic light patterns, minimalist sharp shadows, PBR material textures, clean aesthetic studio lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=450&h=800&fit=crop",
    },
    # 📢 Event / Webinar Announcement
    {
        "name": "Grand Opening",
        "category": "event",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.25,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 48,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.42,
                "font_family": "Inter",
                "font_weight": 300,
                "font_size": 22,
                "color": "#D1D5DB",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.78,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FFFFFF",
                "bg_box": "rgba(79,70,229,0.9)",
            },
        ],
        "prompt_suffix": "grand opening event, elegant ribbon cutting ceremony, falling gold confetti, luxurious atmosphere, warm cinematic lighting, 35mm f/1.4 lens",
        "thumbnail_url": "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=600&h=600&fit=crop",
    },
    {
        "name": "Live Music / Konser",
        "category": "event",
        "aspect_ratio": "16:9",
        "style": "bold",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.30,
                "y": 0.30,
                "font_family": "Poppins",
                "font_weight": 900,
                "font_size": 56,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.30,
                "y": 0.50,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 24,
                "color": "#E5E7EB",
            },
            {
                "role": "cta",
                "x": 0.30,
                "y": 0.72,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 20,
                "color": "#FFFFFF",
                "bg_box": "rgba(220,38,38,0.9)",
            },
        ],
        "prompt_suffix": "live music concert, energetic crowd silhouette, vibrant neon lights, volumetric laser beams, exciting atmosphere, dramatic stage lighting, high ISO film grain",
        "thumbnail_url": "https://images.unsplash.com/photo-1540039155733-d7696d4eb98e?w=800&h=450&fit=crop",
    },
    {
        "name": "Webinar / Online Course",
        "category": "education",
        "aspect_ratio": "1:1",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.15,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 42,
                "color": "#1E3A8A",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.3,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 20,
                "color": "#334155",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Poppins",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FFFFFF",
                "bg_box": "rgba(59,130,246,0.9)",
            },
        ],
        "prompt_suffix": "person working on laptop, bright modern office environment, online learning concept, educational, clean 3D illustration style, isometric angle, ambient occlusion rendering",
        "thumbnail_url": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=600&h=600&fit=crop",
    },
    # 🏢 Real Estate / Property
    {
        "name": "Listing Properti - Square",
        "category": "property",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.75,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 36,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 18,
                "color": "#E5E7EB",
            },
            {
                "role": "cta",
                "x": 0.8,
                "y": 0.15,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 16,
                "color": "#FFFFFF",
                "bg_box": "rgba(234,179,8,0.9)",
            },
        ],
        "prompt_suffix": "modern luxurious house exterior, golden hour sunset lighting, real estate, professional architectural photography, wide angle 14mm lens, HDR lighting, crisp details",
        "thumbnail_url": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=600&fit=crop",
    },
    {
        "name": "Open House - Story",
        "category": "property",
        "aspect_ratio": "9:16",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.15,
                "font_family": "Poppins",
                "font_weight": 600,
                "font_size": 42,
                "color": "#1E293B",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.25,
                "font_family": "Inter",
                "font_weight": 300,
                "font_size": 22,
                "color": "#64748B",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FFFFFF",
                "bg_box": "rgba(15,23,42,0.9)",
            },
        ],
        "prompt_suffix": "bright spacious living room interior design, minimal furniture, large windows with natural diffused daylight, professional interior photography, 24mm tilt-shift lens, photorealistic",
        "thumbnail_url": "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=450&h=800&fit=crop",
    },
    # 🎉 Giveaways / Contest
    {
        "name": "Giveaway - Instagram",
        "category": "giveaway",
        "aspect_ratio": "1:1",
        "style": "playful",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.3,
                "font_family": "Poppins",
                "font_weight": 900,
                "font_size": 64,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.45,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 24,
                "color": "#FEF08A",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.8,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 22,
                "color": "#FFFFFF",
                "bg_box": "rgba(168,85,247,0.9)",
            },
        ],
        "prompt_suffix": "floating gift boxes, dynamic confetti physics, vibrant gradient background, celebration, Cinema 4D 3D render, glossy plastic material, purple and pink lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=600&h=600&fit=crop",
    },
    # 🤝 Hiring / Recruitment
    {
        "name": "Lowongan Kerja - Square",
        "category": "hiring",
        "aspect_ratio": "1:1",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.2,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 48,
                "color": "#0F172A",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.35,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 20,
                "color": "#475569",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Poppins",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FFFFFF",
                "bg_box": "rgba(14,165,233,0.9)",
            },
        ],
        "prompt_suffix": "modern office desk top-down flatlay, laptop, coffee cup, notepad with WE ARE HIRING text graphic, clean corporate aesthetic, soft even studio lighting, sharp focus",
        "thumbnail_url": "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&h=600&fit=crop",
    },
    {
        "name": "We're Hiring - Story",
        "category": "hiring",
        "aspect_ratio": "9:16",
        "style": "bold",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.15,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 52,
                "color": "#FFFFFF",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.28,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 22,
                "color": "#E0E7FF",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 18,
                "color": "#4F46E5",
                "bg_box": "rgba(255,255,255,0.9)",
            },
        ],
        "prompt_suffix": "vibrant 3D abstract geometric shapes, dynamic composition, business recruitment concept, blue and purple gradient, smooth matte materials, raytraced global illumination",
        "thumbnail_url": "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=450&h=800&fit=crop",
    },
    # 💬 Testimonial / Review
    {
        "name": "Testimoni Pelanggan",
        "category": "testimonial",
        "aspect_ratio": "1:1",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.4,
                "font_family": "Playfair Display",
                "font_weight": 500,
                "font_size": 28,
                "color": "#1E293B",
                "shadow": False,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.65,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 18,
                "color": "#64748B",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Inter",
                "font_weight": 500,
                "font_size": 16,
                "color": "#FFFFFF",
                "bg_box": "rgba(0,0,0,0.8)",
            },
        ],
        "prompt_suffix": "3D 5 stars rating icon graphic, subtle soft gradient background, simple clean layout, trust, customer feedback, glossy material finish, soft ambient lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1516245834210-c4c142787335?w=600&h=600&fit=crop",
    },
    # ❄️ Holiday / Festive
    {
        "name": "Ucapan Hari Raya",
        "category": "holiday",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.25,
                "font_family": "Playfair Display",
                "font_weight": 700,
                "font_size": 48,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.45,
                "font_family": "Inter",
                "font_weight": 300,
                "font_size": 22,
                "color": "#F3F4F6",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.8,
                "font_family": "Inter",
                "font_weight": 500,
                "font_size": 16,
                "color": "#111827",
                "bg_box": "rgba(255,255,255,0.9)",
            },
        ],
        "prompt_suffix": "festive decoration, warm bokeh lights, elegant celebration, floating atmospheric gold dust, holiday season, 85mm macro lens, shallow depth of field",
        "thumbnail_url": "https://images.unsplash.com/photo-1543362906-acfc16c67564?w=600&h=600&fit=crop",
    },
    # 📱 Story/Reels General
    {
        "name": "IG Story - Q&A",
        "category": "story",
        "aspect_ratio": "9:16",
        "style": "playful",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.2,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 50,
                "color": "#FFFFFF",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.35,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 22,
                "color": "#E0F2FE",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.7,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 18,
                "color": "#0369A1",
                "bg_box": "rgba(255,255,255,0.95)",
            },
        ],
        "prompt_suffix": "social media questions and answers concept, 3D floating chat bubbles, bright sky blue gradient, fun dynamic composition, softbox lighting, matte plastic textures",
        "thumbnail_url": "https://images.unsplash.com/photo-1616469829581-73993eb86b02?w=450&h=800&fit=crop",
    },
    {
        "name": "Daily Vlog / Update",
        "category": "story",
        "aspect_ratio": "9:16",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.18,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 40,
                "color": "#1E293B",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.30,
                "font_family": "Inter",
                "font_weight": 300,
                "font_size": 20,
                "color": "#64748B",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.88,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 16,
                "color": "#FFFFFF",
                "bg_box": "rgba(30,41,59,0.85)",
            },
        ],
        "prompt_suffix": "clean aesthetic photography, pastel tones, soft natural window light, minimalist lifestyle workspace, morning coffee, 50mm f/1.8 lens, light and airy color grading",
        "thumbnail_url": "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=450&h=800&fit=crop",
    },
    # 🎨 General Purpose
    {
        "name": "Pengumuman Formal",
        "category": "general",
        "aspect_ratio": "1:1",
        "style": "minimalist",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.25,
                "font_family": "Inter",
                "font_weight": 700,
                "font_size": 44,
                "color": "#1E293B",
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.42,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 22,
                "color": "#64748B",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.80,
                "font_family": "Inter",
                "font_weight": 600,
                "font_size": 18,
                "color": "#FFFFFF",
                "bg_box": "rgba(99,102,241,0.9)",
            },
        ],
        "prompt_suffix": "clean professional background, soft subtle gradient, corporate architecture abstraction, modern office vibe, smooth lighting, high-end 3D render",
        "thumbnail_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=600&fit=crop",
    },
    {
        "name": "Creative Agency Banner",
        "category": "general",
        "aspect_ratio": "16:9",
        "style": "bold",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.35,
                "y": 0.35,
                "font_family": "Poppins",
                "font_weight": 800,
                "font_size": 52,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.35,
                "y": 0.52,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 24,
                "color": "#E5E7EB",
            },
            {
                "role": "cta",
                "x": 0.35,
                "y": 0.75,
                "font_family": "Poppins",
                "font_weight": 700,
                "font_size": 20,
                "color": "#FFFFFF",
                "bg_box": "rgba(37,99,235,0.9)",
            },
        ],
        "prompt_suffix": "fluid 3D color waves, abstract colorful liquid pattern, dynamic gradient, eye-catching graphic design, subsurface scattering, Octane render volumetric lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1557683316-973673baf926?w=800&h=450&fit=crop",
    },
    # 🛒 Shopee — Platform-Specific
    {
        "name": "Shopee Flash Sale",
        "category": "sale",
        "aspect_ratio": "1:1",
        "style": "bold",
        "platform": "shopee",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.18, "font_family": "Poppins", "font_weight": 900, "font_size": 56, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.36, "font_family": "Inter", "font_weight": 500, "font_size": 26, "color": "#FEF08A"},
            {"role": "cta", "x": 0.5, "y": 0.82, "font_family": "Poppins", "font_weight": 800, "font_size": 22, "color": "#FFFFFF", "bg_box": "rgba(238,77,45,0.95)"},
        ],
        "prompt_suffix": "Shopee flash sale, vibrant orange and red marketplace tones, shopping cart icons, confetti burst, bright energetic product photography, high contrast studio lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=600&fit=crop",
    },
    {
        "name": "Shopee Produk Baru",
        "category": "product",
        "aspect_ratio": "1:1",
        "style": "minimalist",
        "platform": "shopee",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 700, "font_size": 44, "color": "#1E293B"},
            {"role": "sub_headline", "x": 0.5, "y": 0.28, "font_family": "Inter", "font_weight": 400, "font_size": 20, "color": "#64748B"},
            {"role": "cta", "x": 0.5, "y": 0.85, "font_family": "Poppins", "font_weight": 700, "font_size": 18, "color": "#FFFFFF", "bg_box": "rgba(238,77,45,0.9)"},
        ],
        "prompt_suffix": "new product arrival, clean white product photography, Shopee marketplace listing style, soft shadow, flat lay composition, professional studio lighting 5500K, 50mm f/2.8",
        "thumbnail_url": "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop",
    },
    {
        "name": "Shopee Bundle Hemat",
        "category": "sale",
        "aspect_ratio": "1:1",
        "style": "playful",
        "platform": "shopee",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 800, "font_size": 48, "color": "#1E293B"},
            {"role": "sub_headline", "x": 0.5, "y": 0.30, "font_family": "Inter", "font_weight": 500, "font_size": 22, "color": "#0F172A"},
            {"role": "cta", "x": 0.5, "y": 0.83, "font_family": "Poppins", "font_weight": 700, "font_size": 20, "color": "#FFFFFF", "bg_box": "rgba(234,179,8,0.95)"},
        ],
        "prompt_suffix": "bundle deal products, multiple products arranged together, warm pastel background, cheerful playful composition, soft diffused studio lighting, 50mm product photography",
        "thumbnail_url": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&h=600&fit=crop",
    },
    # 🟢 Tokopedia — Platform-Specific
    {
        "name": "Tokopedia Harbolnas",
        "category": "sale",
        "aspect_ratio": "1:1",
        "style": "bold",
        "platform": "tokopedia",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.18, "font_family": "Poppins", "font_weight": 900, "font_size": 56, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.36, "font_family": "Inter", "font_weight": 500, "font_size": 26, "color": "#D1FAE5"},
            {"role": "cta", "x": 0.5, "y": 0.82, "font_family": "Poppins", "font_weight": 800, "font_size": 22, "color": "#FFFFFF", "bg_box": "rgba(5,150,105,0.95)"},
        ],
        "prompt_suffix": "Tokopedia Harbolnas, green and white marketplace tones, shopping celebration, confetti, vibrant commerce energy, high contrast product studio lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=600&fit=crop",
    },
    {
        "name": "Tokopedia Produk Unggulan",
        "category": "product",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "platform": "tokopedia",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 700, "font_size": 42, "color": "#FFFFFF"},
            {"role": "sub_headline", "x": 0.5, "y": 0.28, "font_family": "Inter", "font_weight": 400, "font_size": 20, "color": "#D1FAE5"},
            {"role": "cta", "x": 0.5, "y": 0.85, "font_family": "Poppins", "font_weight": 600, "font_size": 18, "color": "#FFFFFF", "bg_box": "rgba(5,150,105,0.9)"},
        ],
        "prompt_suffix": "featured product listing, clean elegant product photography, dark green and white tones, professional marketplace style, side lighting with soft shadow, 85mm f/2.0",
        "thumbnail_url": "https://images.unsplash.com/photo-1556742393-d75f468bfcb0?w=600&h=600&fit=crop",
    },
    # 📸 Instagram Feed — Platform-Specific
    {
        "name": "Instagram Feed Fashion",
        "category": "product",
        "aspect_ratio": "4:5",
        "style": "elegant",
        "platform": "instagram",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.80, "font_family": "Playfair Display", "font_weight": 700, "font_size": 38, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.88, "font_family": "Inter", "font_weight": 300, "font_size": 18, "color": "#F3F4F6"},
            {"role": "cta", "x": 0.5, "y": 0.95, "font_family": "Inter", "font_weight": 500, "font_size": 14, "color": "#FFFFFF", "bg_box": "transparent"},
        ],
        "prompt_suffix": "editorial fashion Instagram feed post 4:5 ratio, luxury clothing, soft golden hour backlight, high fashion Vogue aesthetic, 85mm f/1.4 shallow depth of field, muted warm color grade",
        "thumbnail_url": "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=480&h=600&fit=crop",
    },
    {
        "name": "Instagram Feed Beauty",
        "category": "product",
        "aspect_ratio": "4:5",
        "style": "minimalist",
        "platform": "instagram",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.78, "font_family": "Poppins", "font_weight": 600, "font_size": 36, "color": "#1E293B"},
            {"role": "sub_headline", "x": 0.5, "y": 0.87, "font_family": "Inter", "font_weight": 300, "font_size": 18, "color": "#64748B"},
            {"role": "cta", "x": 0.5, "y": 0.94, "font_family": "Inter", "font_weight": 600, "font_size": 14, "color": "#FFFFFF", "bg_box": "rgba(244,114,182,0.85)"},
        ],
        "prompt_suffix": "beauty skincare product Instagram 4:5 post, pastel pink background, clean flat lay, dewey skin texture, caustic light patterns, cosmetics macro photography, 100mm f/2.8",
        "thumbnail_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=480&h=600&fit=crop",
    },
    # 📲 Instagram Story — Platform-Specific
    {
        "name": "IG Story Promo Flash Sale",
        "category": "sale",
        "aspect_ratio": "9:16",
        "style": "playful",
        "platform": "instagram_story",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 900, "font_size": 54, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.30, "font_family": "Inter", "font_weight": 500, "font_size": 24, "color": "#FEF08A"},
            {"role": "cta", "x": 0.5, "y": 0.87, "font_family": "Poppins", "font_weight": 800, "font_size": 22, "color": "#1E293B", "bg_box": "rgba(250,204,21,0.95)"},
        ],
        "prompt_suffix": "Instagram story flash sale vertical 9:16, bright vivid colors, floating discount badges, confetti, energetic commerce, softbox diffused pop colors",
        "thumbnail_url": "https://images.unsplash.com/photo-1620241608701-94efd3cb8534?w=450&h=800&fit=crop",
    },
    {
        "name": "IG Story New Arrival",
        "category": "product",
        "aspect_ratio": "9:16",
        "style": "elegant",
        "platform": "instagram_story",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.12, "font_family": "Playfair Display", "font_weight": 700, "font_size": 46, "color": "#FFFFFF"},
            {"role": "sub_headline", "x": 0.5, "y": 0.24, "font_family": "Inter", "font_weight": 300, "font_size": 20, "color": "#E5E7EB"},
            {"role": "cta", "x": 0.5, "y": 0.88, "font_family": "Inter", "font_weight": 600, "font_size": 16, "color": "#1E293B", "bg_box": "rgba(255,255,255,0.9)"},
        ],
        "prompt_suffix": "new arrival Instagram story vertical, elegant product on dark moody background, subtle rim lighting, luxury brand aesthetic, 85mm tilt-shift, fashion editorial",
        "thumbnail_url": "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=450&h=800&fit=crop",
    },
    {
        "name": "IG Story Hampers",
        "category": "holiday",
        "aspect_ratio": "9:16",
        "style": "elegant",
        "platform": "instagram_story",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.12, "font_family": "Playfair Display", "font_weight": 700, "font_size": 44, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.24, "font_family": "Inter", "font_weight": 300, "font_size": 20, "color": "#FDE68A"},
            {"role": "cta", "x": 0.5, "y": 0.87, "font_family": "Inter", "font_weight": 600, "font_size": 16, "color": "#1E293B", "bg_box": "rgba(251,191,36,0.9)"},
        ],
        "prompt_suffix": "hampers gift basket Indonesia, festive Lebaran Eid decoration, gold ribbon, warm bokeh lights, luxurious celebration atmosphere, 85mm f/1.4, rich warm color grading",
        "thumbnail_url": "https://images.unsplash.com/photo-1543362906-acfc16c67564?w=450&h=800&fit=crop",
    },
    # 💬 WhatsApp — Platform-Specific
    {
        "name": "WhatsApp Broadcast Promo",
        "category": "sale",
        "aspect_ratio": "9:16",
        "style": "bold",
        "platform": "whatsapp",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 900, "font_size": 52, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.32, "font_family": "Inter", "font_weight": 500, "font_size": 24, "color": "#D1FAE5"},
            {"role": "cta", "x": 0.5, "y": 0.85, "font_family": "Poppins", "font_weight": 700, "font_size": 22, "color": "#FFFFFF", "bg_box": "rgba(37,211,102,0.95)"},
        ],
        "prompt_suffix": "WhatsApp broadcast promotion, green and white tones, mobile-first vertical format, clear readable text space, bold product display, bright friendly lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=450&h=800&fit=crop",
    },
    {
        "name": "WhatsApp Flash Sale Status",
        "category": "sale",
        "aspect_ratio": "9:16",
        "style": "playful",
        "platform": "whatsapp",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 800, "font_size": 50, "color": "#1E293B"},
            {"role": "sub_headline", "x": 0.5, "y": 0.30, "font_family": "Inter", "font_weight": 500, "font_size": 22, "color": "#374151"},
            {"role": "cta", "x": 0.5, "y": 0.86, "font_family": "Poppins", "font_weight": 700, "font_size": 20, "color": "#FFFFFF", "bg_box": "rgba(37,211,102,0.95)"},
        ],
        "prompt_suffix": "WhatsApp status flash sale, bright yellow and green cheerful palette, floating price tags, fun bouncy energy, clear mobile-readable composition, studio lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1620241608701-94efd3cb8534?w=450&h=800&fit=crop",
    },
    # 🎁 Hampers / Seasonal
    {
        "name": "Hampers Lebaran Elegan",
        "category": "holiday",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.22, "font_family": "Playfair Display", "font_weight": 700, "font_size": 46, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.40, "font_family": "Inter", "font_weight": 300, "font_size": 20, "color": "#FDE68A"},
            {"role": "cta", "x": 0.5, "y": 0.82, "font_family": "Inter", "font_weight": 600, "font_size": 17, "color": "#1E293B", "bg_box": "rgba(251,191,36,0.9)"},
        ],
        "prompt_suffix": "Lebaran Eid hampers gift basket, luxurious gold ribbon, ketupat decoration, warm bokeh lights, dark moody elegant background, 85mm f/1.4, rich golden color grading",
        "thumbnail_url": "https://images.unsplash.com/photo-1606914469633-bd44a5974565?w=600&h=600&fit=crop",
    },
    {
        "name": "Hampers Natal",
        "category": "holiday",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.20, "font_family": "Playfair Display", "font_weight": 700, "font_size": 46, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.36, "font_family": "Inter", "font_weight": 300, "font_size": 20, "color": "#D1FAE5"},
            {"role": "cta", "x": 0.5, "y": 0.82, "font_family": "Inter", "font_weight": 600, "font_size": 17, "color": "#FFFFFF", "bg_box": "rgba(220,38,38,0.9)"},
        ],
        "prompt_suffix": "Christmas hampers gift box, red and green festive decor, pine branches, snow bokeh, warm candle light, luxurious holiday packaging, 85mm f/1.4",
        "thumbnail_url": "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600&h=600&fit=crop",
    },
    # 👗 Fashion / Apparel Seller
    {
        "name": "Fashion Diskon Story",
        "category": "product",
        "aspect_ratio": "9:16",
        "style": "bold",
        "platform": "instagram_story",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.12, "font_family": "Poppins", "font_weight": 900, "font_size": 52, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.25, "font_family": "Inter", "font_weight": 400, "font_size": 22, "color": "#FEF9EE"},
            {"role": "cta", "x": 0.5, "y": 0.87, "font_family": "Poppins", "font_weight": 700, "font_size": 20, "color": "#1E293B", "bg_box": "rgba(250,204,21,0.95)"},
        ],
        "prompt_suffix": "fashion sale Instagram story vertical, model wearing stylish outfit, vibrant color-blocked background, bold graphic overlay, editorial fashion photography 50mm f/2",
        "thumbnail_url": "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=450&h=800&fit=crop",
    },
    # 💄 Beauty / Skincare Seller
    {
        "name": "Beauty Skincare Square",
        "category": "product",
        "aspect_ratio": "1:1",
        "style": "minimalist",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 600, "font_size": 42, "color": "#374151"},
            {"role": "sub_headline", "x": 0.5, "y": 0.27, "font_family": "Inter", "font_weight": 300, "font_size": 20, "color": "#9CA3AF"},
            {"role": "cta", "x": 0.5, "y": 0.85, "font_family": "Inter", "font_weight": 600, "font_size": 16, "color": "#FFFFFF", "bg_box": "rgba(244,114,182,0.9)"},
        ],
        "prompt_suffix": "skincare product flat lay, pastel pink marble background, dropper bottles and cream jars, macro caustic light patterns, minimal clean aesthetic, 100mm f/2.8",
        "thumbnail_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop",
    },
    # 🍱 F&B Hampers Seller
    {
        "name": "Hampers Makanan Premium",
        "category": "food",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.18, "font_family": "Playfair Display", "font_weight": 700, "font_size": 44, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.33, "font_family": "Inter", "font_weight": 300, "font_size": 20, "color": "#FDE68A"},
            {"role": "cta", "x": 0.5, "y": 0.83, "font_family": "Inter", "font_weight": 600, "font_size": 17, "color": "#1E293B", "bg_box": "rgba(251,191,36,0.9)"},
        ],
        "prompt_suffix": "premium food hampers, gourmet snacks arranged beautifully, luxury basket, warm Rembrandt lighting, dark elegant background, appetizing food photography, 85mm f/2.0",
        "thumbnail_url": "https://images.unsplash.com/photo-1606914469633-bd44a5974565?w=600&h=600&fit=crop",
    },
    # 📣 General Promo / Announcement
    {
        "name": "Diskon Persen Square",
        "category": "sale",
        "aspect_ratio": "1:1",
        "style": "bold",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.20, "font_family": "Poppins", "font_weight": 900, "font_size": 80, "color": "#FFFFFF", "shadow": True},
            {"role": "sub_headline", "x": 0.5, "y": 0.42, "font_family": "Inter", "font_weight": 500, "font_size": 28, "color": "#FEF08A"},
            {"role": "cta", "x": 0.5, "y": 0.82, "font_family": "Poppins", "font_weight": 700, "font_size": 22, "color": "#FFFFFF", "bg_box": "rgba(239,68,68,0.95)"},
        ],
        "prompt_suffix": "big percentage discount promo, bold numbers, vibrant red and yellow palette, dynamic energy, floating price tags, high contrast studio product lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=600&fit=crop",
    },
    {
        "name": "Bundle Deal Hemat",
        "category": "sale",
        "aspect_ratio": "1:1",
        "style": "playful",
        "default_text_layers": [
            {"role": "headline", "x": 0.5, "y": 0.15, "font_family": "Poppins", "font_weight": 800, "font_size": 48, "color": "#1E293B"},
            {"role": "sub_headline", "x": 0.5, "y": 0.30, "font_family": "Inter", "font_weight": 500, "font_size": 22, "color": "#374151"},
            {"role": "cta", "x": 0.5, "y": 0.83, "font_family": "Poppins", "font_weight": 700, "font_size": 20, "color": "#FFFFFF", "bg_box": "rgba(234,179,8,0.95)"},
        ],
        "prompt_suffix": "product bundle deal, multiple items arranged together, pastel yellow background, cheerful playful composition, clean product photography, soft diffused studio lighting",
        "thumbnail_url": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&h=600&fit=crop",
    },
    {
        "name": "Quotes / Motivasi",
        "category": "general",
        "aspect_ratio": "1:1",
        "style": "elegant",
        "default_text_layers": [
            {
                "role": "headline",
                "x": 0.5,
                "y": 0.45,
                "font_family": "Playfair Display",
                "font_weight": 600,
                "font_size": 36,
                "color": "#FFFFFF",
                "shadow": True,
            },
            {
                "role": "sub_headline",
                "x": 0.5,
                "y": 0.65,
                "font_family": "Inter",
                "font_weight": 400,
                "font_size": 18,
                "color": "#E5E7EB",
            },
            {
                "role": "cta",
                "x": 0.5,
                "y": 0.85,
                "font_family": "Inter",
                "font_weight": 500,
                "font_size": 16,
                "color": "#FFFFFF",
                "bg_box": "transparent",
            },
        ],
        "prompt_suffix": "breathtaking epic mountain landscape, golden sunrise, moody nature photography, cinematic color grading, wide angle 16mm lens, anamorphic lens flare",
        "thumbnail_url": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&h=600&fit=crop",
    },
]


async def seed():
    """Insert all seed templates into the database."""
    async with AsyncSessionLocal() as session:
        # Fetch existing templates to prevent duplicates
        result = await session.execute(select(Template))
        existing_templates = {t.name: t for t in result.scalars().all()}

        added = 0
        updated = 0

        for tmpl_data in TEMPLATES:
            if tmpl_data["name"] in existing_templates:
                # Update existing template
                tmpl = existing_templates[tmpl_data["name"]]
                tmpl.category = tmpl_data["category"]
                tmpl.aspect_ratio = tmpl_data["aspect_ratio"]
                tmpl.style = tmpl_data["style"]
                tmpl.default_text_layers = tmpl_data["default_text_layers"]
                tmpl.prompt_suffix = tmpl_data.get("prompt_suffix")
                tmpl.thumbnail_url = tmpl_data.get("thumbnail_url")
                tmpl.platform = tmpl_data.get("platform")
                updated += 1
            else:
                # Insert new template
                tmpl = Template(
                    id=uuid.uuid4(),
                    name=tmpl_data["name"],
                    category=tmpl_data["category"],
                    aspect_ratio=tmpl_data["aspect_ratio"],
                    style=tmpl_data["style"],
                    default_text_layers=tmpl_data["default_text_layers"],
                    prompt_suffix=tmpl_data.get("prompt_suffix"),
                    thumbnail_url=tmpl_data.get("thumbnail_url"),
                    platform=tmpl_data.get("platform"),
                )
                session.add(tmpl)
                added += 1

        await session.commit()
        print(
            f"✅ Seeded {added} new templates and updated {updated} existing templates successfully!"
        )


if __name__ == "__main__":
    asyncio.run(seed())
