"""add folders table

Revision ID: 19e17b7eb11b
Revises: 95b0eaf5fd60
Create Date: 2026-03-27 10:36:49.789988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e17b7eb11b'
down_revision: Union[str, None] = '95b0eaf5fd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.drop_index('ix_ai_tool_jobs_status_created_at', table_name='ai_tool_jobs')
    op.drop_index('ix_ai_tool_jobs_user_created_at', table_name='ai_tool_jobs')
    op.drop_index('uq_ai_tool_jobs_user_idempotency_key', table_name='ai_tool_jobs')
    op.add_column('brand_kits', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_brand_kits_folder_id'), 'brand_kits', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'brand_kits', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_projects_folder_id'), 'projects', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_template_favorite_user_submission', 'template_favorites', type_='unique')
    op.drop_index('ix_template_submissions_status_category', table_name='template_submissions')
    op.drop_constraint('uq_template_submission_version', 'template_versions', type_='unique')
    op.add_column('users', sa.Column('reset_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.create_unique_constraint('uq_template_submission_version', 'template_versions', ['template_submission_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_template_submissions_status_category', 'template_submissions', ['status', 'category'], unique=False)
    op.create_unique_constraint('uq_template_favorite_user_submission', 'template_favorites', ['user_id', 'template_submission_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_folder_id'), table_name='projects')
    op.drop_column('projects', 'folder_id')
    op.drop_constraint(None, 'brand_kits', type_='foreignkey')
    op.drop_index(op.f('ix_brand_kits_folder_id'), table_name='brand_kits')
    op.drop_column('brand_kits', 'folder_id')
    op.create_index('uq_ai_tool_jobs_user_idempotency_key', 'ai_tool_jobs', ['user_id', 'idempotency_key'], unique=True)
    op.create_index('ix_ai_tool_jobs_user_created_at', 'ai_tool_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_ai_tool_jobs_status_created_at', 'ai_tool_jobs', ['status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
