"""Update default credits_remaining from 10 to 100

Revision ID: 462447985d3b
Revises: 715437099b9a
Create Date: 2026-03-16 13:16:36.427555

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '462447985d3b'
down_revision: Union[str, None] = '715437099b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
