"""Add brand strategy to brand kit

Revision ID: 4a69752dc731
Revises: f4349a14022b
Create Date: 2026-03-21 09:21:47.245318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a69752dc731'
down_revision: Union[str, None] = 'f4349a14022b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_kits', sa.Column('brand_strategy', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_kits', 'brand_strategy')
    # ### end Alembic commands ###
