"""add quantum_layout to jobs

Revision ID: 715437099b9a
Revises: f7a2b3c4d5e6
Create Date: 2026-03-16 11:37:37.383366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715437099b9a'
down_revision: Union[str, None] = 'f7a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('quantum_layout', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'quantum_layout')
    # ### end Alembic commands ###
