"""Add folder_id to jobs and ai_tool_results

Revision ID: 84609b232396
Revises: 19e17b7eb11b
Create Date: 2026-03-27 10:49:52.531270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84609b232396'
down_revision: Union[str, None] = '19e17b7eb11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_tool_results', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_tool_results_folder_id'), 'ai_tool_results', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'ai_tool_results', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.add_column('jobs', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_folder_id'), 'jobs', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_folder_id'), table_name='jobs')
    op.drop_column('jobs', 'folder_id')
    op.drop_constraint(None, 'ai_tool_results', type_='foreignkey')
    op.drop_index(op.f('ix_ai_tool_results_folder_id'), table_name='ai_tool_results')
    op.drop_column('ai_tool_results', 'folder_id')
    # ### end Alembic commands ###
