"""Add design_exports table for backend-owned export event tracking.

Revision ID: a8b7c6d5e4f3
Revises: f7a2b3c4d5e6
Create Date: 2026-05-13 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a8b7c6d5e4f3"
down_revision = "f7a2b3c4d5e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "design_exports",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("design_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("export_format", sa.String(50), nullable=False),
        sa.Column("target_platform", sa.String(50), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["design_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["ai_tool_jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_design_exports_created_at", "design_exports", ["created_at"], unique=False)
    op.create_index("ix_design_exports_design_id", "design_exports", ["design_id"], unique=False)
    op.create_index("ix_design_exports_job_id", "design_exports", ["job_id"], unique=False)
    op.create_index("ix_design_exports_success", "design_exports", ["success"], unique=False)
    op.create_index("ix_design_exports_user_id", "design_exports", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_design_exports_user_id", table_name="design_exports")
    op.drop_index("ix_design_exports_success", table_name="design_exports")
    op.drop_index("ix_design_exports_job_id", table_name="design_exports")
    op.drop_index("ix_design_exports_design_id", table_name="design_exports")
    op.drop_index("ix_design_exports_created_at", table_name="design_exports")
    op.drop_table("design_exports")
    # ### end Alembic commands ###
