"""Add logos and typography to BrandKit

Revision ID: e3f9a83f5cc6
Revises: bf0521e89d9b
Create Date: 2026-03-14 11:35:57.928530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3f9a83f5cc6"
down_revision: Union[str, None] = "bf0521e89d9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("brand_kits", sa.Column("logos", sa.JSON(), nullable=True))
    op.add_column("brand_kits", sa.Column("typography", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("brand_kits", "typography")
    op.drop_column("brand_kits", "logos")
    # ### end Alembic commands ###
